# Day 1

import pandas as pd

data = {
    'employee_id': [1, 2, 3, 4, 5, 6],
    'department':  ['Sales', 'Sales', 'Tech', 'Tech', 'Tech', 'HR'],
    'salary':      [70000, 90000, 85000, 85000, 120000, 60000]
}

df = pd.DataFrame(data)
```

**Write a function that returns the top 2 unique salaries per department.**

Expected output:
```
  department  salary
0         HR   60000
1      Sales   90000
2      Sales   70000
3       Tech  120000
4       Tech   85000

In [18]:
import pandas as pd 

data = {
    'employee_id': [1, 2, 3, 4, 5, 6],
    'department':  ['Sales', 'Sales', 'Tech', 'Tech', 'Tech', 'HR'],
    'salary':      [70000, 90000, 85000, 85000, 120000, 60000]
}

df = pd.DataFrame(data)

df.drop_duplicates(subset = ['salary'], inplace = True)
print(df)

   employee_id department  salary
0            1      Sales   70000
1            2      Sales   90000
2            3       Tech   85000
4            5       Tech  120000
5            6         HR   60000

In [22]:
df.drop_duplicates(subset = ['department','salary'], inplace = True)

grouped_df =  df.groupby("department")['salary'].nlargest(2).reset_index()
grouped_df = grouped_df[['department','salary']]
grouped_df

  department  salary
0         HR   60000
1      Sales   90000
2      Sales   70000
3       Tech  120000
4       Tech   85000

data = {
    'order_id':    [1, 2, 3, 4, 5, 6, 7],
    'customer_id': [101, 101, 102, 103, 101, 102, 103],
    'order_date':  ['2024-01-01', '2024-01-15', '2024-01-03',
                    '2024-01-07', '2024-02-01', '2024-02-10', '2024-02-15'],
    'amount':      [250, 180, 320, 150, 400, 210, 90]
}
```

**Customer 103 is a low value customer — they've spent less than $300 total. Find all customers whose total spending exceeds $300, and return their customer_id and total amount spent, sorted highest to lowest.**

Expected output:
```
   customer_id  total_amount
0          101           830
1          102           530

In [35]:
data = {
    'order_id':    [1, 2, 3, 4, 5, 6, 7],
    'customer_id': [101, 101, 102, 103, 101, 102, 103],
    'order_date':  ['2024-01-01', '2024-01-15', '2024-01-03',
                    '2024-01-07', '2024-02-01', '2024-02-10', '2024-02-15'],
    'amount':      [250, 180, 320, 150, 400, 210, 90]
}


df = pd.DataFrame(data)
grouped_customer = df.groupby(['customer_id'])['amount'].agg("sum").reset_index()
grouped_customer =grouped_customer[grouped_customer['amount'] > 300].sort_values('amount', ascending = False)
grouped_customer

   customer_id  amount
0          101     830
1          102     530

data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'subject':    ['Math', 'Math', 'Science', 'Science', 
                   'Math', 'Science', 'Math', 'Science'],
    'score':      [85, 92, 78, 95, 88, 72, 91, 85]
}
```

**Find the average score per subject. Return only subjects where the average score is above 85. Round the average to 2 decimal places.**

Expected output:
```
   subject  avg_score
0     Math      89.00

In [48]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'subject':    ['Math', 'Math', 'Science', 'Science', 
                   'Math', 'Science', 'Math', 'Science'],
    'score':      [85, 92, 78, 95, 88, 72, 91, 85]
}

df = pd.DataFrame(data)
df_grouped = df.groupby('subject')['score'].agg('mean').reset_index()
df_grouped.columns = ['subject','avgscore']
df_grouped = df_grouped[df_grouped['avgscore'] > 85]
df_grouped['avgscore'] = df_grouped['avgscore'].round(2)
df_grouped

  subject  avgscore
0    Math      89.0

data = {
    'employee_id': [1, 2, 3, 4, 5, 6],
    'department':  ['Sales', 'Sales', 'Tech', 'Tech', 'HR', 'HR'],
    'salary':      [70000, 90000, 85000, 120000, 60000, 75000],
    'hire_date':   ['2020-01-01', '2019-03-15', '2021-06-01', 
                    '2018-09-01', '2022-01-15', '2017-11-30']
}


For each department, find the highest paid employee's name — wait, there's no name column. Find their employee_id and how many years they've been with the company as of today. Round years to 1 decimal place.

Requirements:

Highest salary per department
Return employee_id, department, salary, years_at_company
Round years to 1 decimal

In [93]:
data = {
    'employee_id': [1, 2, 3, 4, 5, 6],
    'department':  ['Sales', 'Sales', 'Tech', 'Tech', 'HR', 'HR'],
    'salary':      [70000, 90000, 85000, 120000, 60000, 75000],
    'hire_date':   ['2020-01-01', '2019-03-15', '2021-06-01', 
                    '2018-09-01', '2022-01-15', '2017-11-30']
}

df = pd.DataFrame(data)
df['hire_date'] = pd.to_datetime(df['hire_date'] )
df['days'] =  (pd.Timestamp.now() - df['hire_date']).dt.days
df['years'] = round(df['days'] / 365.25,2)
df_gped = df.groupby('department')['salary'].idxmax()
final_df  =  df.loc[df_gped]
final_df = final_df[['employee_id', 'years']]
final_df

   employee_id  years
5            6   8.30
1            2   7.01
3            4   7.54